{"uid":"5e0ba601446fd466","name":"test_few_negative_exceptions_and_errors","fullName":"test_allure_section#test_few_negative_exceptions_and_errors","historyId":"291f0cab6d3fae0a490e28af3510283e","time":{"start":1706380843753,"stop":1706380843758,"duration":5},"status":"failed","statusMessage":"AssertionError: Occurred.\n\nMultiple exceptions occurred:\n1. AssertionError: AssertionError here\n2. Exception: Failed exception here\n3. ZeroDivisionError: ZeroDivisionError here","statusTrace":">   ???\n\n/Users/timofeev/PycharmProjects/allure_section/test/test_allure_section.py:71: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <allure_section._allure_section.SectionContext object at 0x10c59b880>\nexc_type = <class 'AssertionError'>, exc_val = MultipleExceptions()\nexc_tb = None\n\n    def __exit__(self, exc_type, exc_val, exc_tb):\n        \"\"\"Exit from the section context\"\"\"\n        logger.info(f\"Exit from section <{self.title}>\")\n        if self._exceptions:\n            if len(self._exceptions) == 1:\n                exception = self._exceptions[0]\n                exc_type = type(exception)\n                exc_val = exception\n                exc_tb = exception.__traceback__\n            else:\n                exc_type = self._exc_type if self._exc_type in [type(e) for e in self._exceptions] else Exception\n                exc_val = MultipleExceptions(self._exceptions)\n    \n        plugin_manager.hook.stop_step(uuid=self.uuid, title=self.title, exc_type=exc_type, exc_val=exc_val,\n                                      exc_tb=exc_tb)\n        if exc_type:\n>           raise exc_type(exc_val)\nE           AssertionError: Occurred.\nE           \nE           Multiple exceptions occurred:\nE           1. AssertionError: AssertionError here\nE           2. Exception: Failed exception here\nE           3. ZeroDivisionError: ZeroDivisionError here\n\n../allure_section/_allure_section.py:92: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"AssertionError: Occurred.\n\nMultiple exceptions occurred:\n1. AssertionError: AssertionError here\n2. Exception: Failed exception here\n3. ZeroDivisionError: ZeroDivisionError here","statusTrace":">   ???\n\n/Users/timofeev/PycharmProjects/allure_section/test/test_allure_section.py:71: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <allure_section._allure_section.SectionContext object at 0x10c59b880>\nexc_type = <class 'AssertionError'>, exc_val = MultipleExceptions()\nexc_tb = None\n\n    def __exit__(self, exc_type, exc_val, exc_tb):\n        \"\"\"Exit from the section context\"\"\"\n        logger.info(f\"Exit from section <{self.title}>\")\n        if self._exceptions:\n            if len(self._exceptions) == 1:\n                exception = self._exceptions[0]\n                exc_type = type(exception)\n                exc_val = exception\n                exc_tb = exception.__traceback__\n            else:\n                exc_type = self._exc_type if self._exc_type in [type(e) for e in self._exceptions] else Exception\n                exc_val = MultipleExceptions(self._exceptions)\n    \n        plugin_manager.hook.stop_step(uuid=self.uuid, title=self.title, exc_type=exc_type, exc_val=exc_val,\n                                      exc_tb=exc_tb)\n        if exc_type:\n>           raise exc_type(exc_val)\nE           AssertionError: Occurred.\nE           \nE           Multiple exceptions occurred:\nE           1. AssertionError: AssertionError here\nE           2. Exception: Failed exception here\nE           3. ZeroDivisionError: ZeroDivisionError here\n\n../allure_section/_allure_section.py:92: AssertionError","steps":[{"name":"Positive test section","time":{"start":1706380843753,"stop":1706380843758,"duration":5},"status":"broken","statusMessage":"AssertionError: Occurred.\n\nMultiple exceptions occurred:\n1. AssertionError: AssertionError here\n2. Exception: Failed exception here\n3. ZeroDivisionError: ZeroDivisionError here\n","steps":[{"name":"First step validation","time":{"start":1706380843754,"stop":1706380843754,"duration":0},"status":"failed","statusMessage":"AssertionError: AssertionError here\n","statusTrace":"  File \"/Users/timofeev/PycharmProjects/allure_section/allure_section/_allure_section.py\", line 104, in step\n    yield\n  File \"/Users/timofeev/PycharmProjects/allure_section/test/test_allure_section.py\", line 63, in test_few_negative_exceptions_and_errors\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"Second step validation","time":{"start":1706380843754,"stop":1706380843754,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"Third step validation","time":{"start":1706380843754,"stop":1706380843754,"duration":0},"status":"broken","statusMessage":"Exception: Failed exception here\n","statusTrace":"  File \"/Users/timofeev/PycharmProjects/allure_section/allure_section/_allure_section.py\", line 104, in step\n    yield\n  File \"/Users/timofeev/PycharmProjects/allure_section/test/test_allure_section.py\", line 67, in test_few_negative_exceptions_and_errors\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"Fourth step validation","time":{"start":1706380843756,"stop":1706380843756,"duration":0},"status":"broken","statusMessage":"ZeroDivisionError: ZeroDivisionError here\n","statusTrace":"  File \"/Users/timofeev/PycharmProjects/allure_section/allure_section/_allure_section.py\", line 104, in step\n    yield\n  File \"/Users/timofeev/PycharmProjects/allure_section/test/test_allure_section.py\", line 69, in test_few_negative_exceptions_and_errors\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":0,"hasContent":true,"attachmentStep":false},{"name":"Fifth step validation","time":{"start":1706380843758,"stop":1706380843758,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"stepsCount":5,"attachmentsCount":0,"hasContent":true,"attachmentStep":false}],"attachments":[{"uid":"b934be33d1558671","name":"log","source":"b934be33d1558671.txt","type":"text/plain","size":259}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":6,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[],"labels":[{"name":"suite","value":"test_allure_section"},{"name":"host","value":"MacBook-Pro-Alexander.local"},{"name":"thread","value":"44357-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test_allure_section"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"5e0ba601446fd466.json","parameterValues":[]}