{"uid":"a3376cd7814d96ce","name":"test_few_broken_steps","fullName":"test_allure_section#test_few_broken_steps","historyId":"95eebc0084d84d1ee71eb4c49ccb9c8f","time":{"start":1706461373911,"stop":1706461373913,"duration":2},"status":"broken","statusMessage":"Exception: Occurred.\n\nMultiple exceptions occurred:\n1. Exception: Can't validate Pin State\n2. Exception: Can't validate Consumer reaction","statusTrace":"def test_few_broken_steps():\n        with allure_section(\"Validate Electrical Power System activation\") as section:\n            with section.step(\"Validate Control Msg was sent\"):\n                pass\n            with section.step(\"Validate Pin State is On\"):\n                raise Exception(\"Can't validate Pin State\")\n            with section.step(\"Validate Consumer reaction\"):\n>               raise Exception(\"Can't validate Consumer reaction\")\n\ntest_allure_section.py:41: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <allure_section._allure_section.SectionContext object at 0x1087ab070>\nexc_type = <class 'Exception'>, exc_val = MultipleExceptions(), exc_tb = None\n\n    def __exit__(self, exc_type, exc_val, exc_tb):\n        \"\"\"Exit from the section context\"\"\"\n        if self._exceptions:\n            if len(self._exceptions) == 1:\n                exception = self._exceptions[0]\n                exc_type = type(exception)\n                exc_val = exception\n                exc_tb = exception.__traceback__\n            elif self._exc_type in [type(e) for e in self._exceptions]:\n                exc_type = self._exc_type\n                exc_val = MultipleErrors(self._exceptions)\n                exc_tb = MultipleErrors(self._exceptions).__traceback__\n            else:\n                exc_type = Exception\n                exc_val = MultipleExceptions(self._exceptions)\n                exc_tb = MultipleExceptions(self._exceptions).__traceback__\n    \n        plugin_manager.hook.stop_step(uuid=self.uuid, title=self.title, exc_type=exc_type, exc_val=exc_val,\n                                      exc_tb=exc_tb)\n        if exc_type:\n>           raise exc_type(exc_val)\nE           Exception: Occurred.\nE           \nE           Multiple exceptions occurred:\nE           1. Exception: Can't validate Pin State\nE           2. Exception: Can't validate Consumer reaction\n\n../../allure_section/_allure_section.py:105: Exception","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"broken","statusMessage":"Exception: Occurred.\n\nMultiple exceptions occurred:\n1. Exception: Can't validate Pin State\n2. Exception: Can't validate Consumer reaction","statusTrace":"def test_few_broken_steps():\n        with allure_section(\"Validate Electrical Power System activation\") as section:\n            with section.step(\"Validate Control Msg was sent\"):\n                pass\n            with section.step(\"Validate Pin State is On\"):\n                raise Exception(\"Can't validate Pin State\")\n            with section.step(\"Validate Consumer reaction\"):\n>               raise Exception(\"Can't validate Consumer reaction\")\n\ntest_allure_section.py:41: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <allure_section._allure_section.SectionContext object at 0x1087ab070>\nexc_type = <class 'Exception'>, exc_val = MultipleExceptions(), exc_tb = None\n\n    def __exit__(self, exc_type, exc_val, exc_tb):\n        \"\"\"Exit from the section context\"\"\"\n        if self._exceptions:\n            if len(self._exceptions) == 1:\n                exception = self._exceptions[0]\n                exc_type = type(exception)\n                exc_val = exception\n                exc_tb = exception.__traceback__\n            elif self._exc_type in [type(e) for e in self._exceptions]:\n                exc_type = self._exc_type\n                exc_val = MultipleErrors(self._exceptions)\n                exc_tb = MultipleErrors(self._exceptions).__traceback__\n            else:\n                exc_type = Exception\n                exc_val = MultipleExceptions(self._exceptions)\n                exc_tb = MultipleExceptions(self._exceptions).__traceback__\n    \n        plugin_manager.hook.stop_step(uuid=self.uuid, title=self.title, exc_type=exc_type, exc_val=exc_val,\n                                      exc_tb=exc_tb)\n        if exc_type:\n>           raise exc_type(exc_val)\nE           Exception: Occurred.\nE           \nE           Multiple exceptions occurred:\nE           1. Exception: Can't validate Pin State\nE           2. Exception: Can't validate Consumer reaction\n\n../../allure_section/_allure_section.py:105: Exception","steps":[{"name":"Validate Electrical Power System activation","time":{"start":1706461373912,"stop":1706461373912,"duration":0},"status":"broken","statusMessage":"Exception: Occurred.\n\nMultiple exceptions occurred:\n1. Exception: Can't validate Pin State\n2. Exception: Can't validate Consumer reaction\n","steps":[{"name":"Validate Control Msg was sent","time":{"start":1706461373912,"stop":1706461373912,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":false},{"name":"Validate Pin State is On","time":{"start":1706461373912,"stop":1706461373912,"duration":0},"status":"broken","statusMessage":"Exception: Can't validate Pin State\n","statusTrace":"  File \"/Users/timofeev/PycharmProjects/allure_section/allure_section/_allure_section.py\", line 116, in step\n    yield\n  File \"/Users/timofeev/PycharmProjects/allure_section/examples/test_example/test_allure_section.py\", line 39, in test_few_broken_steps\n    raise Exception(\"Can't validate Pin State\")\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":true},{"name":"Validate Consumer reaction","time":{"start":1706461373912,"stop":1706461373912,"duration":0},"status":"broken","statusMessage":"Exception: Can't validate Consumer reaction\n","statusTrace":"  File \"/Users/timofeev/PycharmProjects/allure_section/allure_section/_allure_section.py\", line 116, in step\n    yield\n  File \"/Users/timofeev/PycharmProjects/allure_section/examples/test_example/test_allure_section.py\", line 41, in test_few_broken_steps\n    raise Exception(\"Can't validate Consumer reaction\")\n","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":0,"attachmentStep":false,"stepsCount":0,"hasContent":true}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":0,"attachmentStep":false,"stepsCount":3,"hasContent":true}],"attachments":[],"parameters":[],"shouldDisplayMessage":true,"attachmentsCount":0,"attachmentStep":false,"stepsCount":4,"hasContent":true},"afterStages":[],"labels":[{"name":"suite","value":"test_allure_section"},{"name":"host","value":"MacBook-Pro-Alexander.local"},{"name":"thread","value":"53877-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"test_allure_section"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"a3376cd7814d96ce.json","parameterValues":[]}